server {
    listen 80;
    server_name localhost;

    # Główny katalog, z którego Nginx serwuje pliki
    root /usr/share/nginx/html;

    # --- KLUCZOWA KONFIGURACJA DLA REACT ROUTER (SPA) ---
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Opcjonalnie: Nagłówki CORS, jeśli potrzebujesz (odkomentuj jeśli konieczne)
    # add_header Access-Control-Allow-Origin *;
}